sites:
  listsites: ['foo1.com', 'foo2.com', 'foo3.com']

config:
  localurlpath: "/Users/micke/Dropbox/KOD/_DEV/KringPing/"
  remoteurlpath: "/var/www/yoursite.com/public/stats/ping/"
  time_between_checks: 60 #seconds 


sftp:
  username: www-user
  password: password123
  host: 11.22.33.44
  port: 22


email:
  username: "user.name@site.com"
  password: "password123"
  server: "smtp-relay.sendinblue.com: 587"
  mailto: "me@site.com"
